management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: configprops, env, health

spring:
  data:
    mongodb:
      database: candidates
      uri: mongodb+srv://${MONGO_USER:user}:${MONGO_PASS:user}@${MONGO_HOST:host}/candidates?retryWrites=true&w=majority&serverSelectionTimeoutMS=2000&connectTimeoutMS=2000
  mail:
    host: send.one.com
    password: ${SMTP_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
          timeout: 5000
          writetimeout: 5000
    username: candidates-career@candidates-career.tech
  rabbitmq:
    host: ${RABBIT_HOST}
    username: ${RABBIT_USER}
    password: ${RABBIT_PASSWORD}
    virtual-host: ${RABBIT_VHOST}

app:
  host:
    front-end: https://candidates-app-prd.herokuapp.com/
    back-end: https://candidates-career.herokuapp.com
  linkedin:
    client-id: ${LINKEDIN_CLIENT_ID}
    clientSecret: ${LINKEDIN_CLIENT_SECRET}
    redirectHost: https://candidates-career.herokuapp.com/
  github:
    client-id: ${GITHUB_CLIENT_ID}
    clientSecret: ${GITHUB_CLIENT_SECRET}
  rest:
    read-timeout-in-ms: 5000
    connect-timeout-in-ms: 5000
  security:
    email-verification-enabled: true
    jwt-secret: ${JWT_SECRET}
  queue:
    candidate:
      exchange: candidate.exchange
      routing-key: candidate.routingkey
      candidate-code-queue: candidate.code
  upload:
    resume:
      max-size: 2000000
      extensions-allowed: pdf, docx, doc, odt
