spring:
  data:
    mongodb:
      database: candidates
      uri: mongodb+srv://${MONGO_USER}:${MONGO_PASS}@${MONGO_HOST}/candidates?retryWrites=true&w=majority&serverSelectionTimeoutMS=2000&connectTimeoutMS=2000
app:
  linkedin:
    redirectHost: https://candidates-career-dev.herokuapp.com/
  security:
    verification-host: https://candidates-career-dev.herokuapp.com
  queue:
    candidate:
      candidate-code-queue: candidate.code.develop