spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost:27017}/candidates?serverSelectionTimeoutMS=2000&connectTimeoutMS=2000
app:
  linkedin:
    redirectHost: http://localhost:8080
  security:
    verification-host: http://localhost:8080
  queue:
    candidate:
      exchange: candidate.exchange.local
      routing-key: candidate.routingkey.local
      candidate-code-queue: candidate.code.local