app:
  host:
    front-end: https://candidates-app-dev.herokuapp.com/
    back-end: https://candidates-career-dev.herokuapp.com
  linkedin:
    redirectHost: https://candidates-career-dev.herokuapp.com/
  queue:
    candidate:
      exchange: candidate.exchange.develop
      routing-key: candidate.routingkey.develop
      candidate-code-queue: candidate.code.develop