name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Get Version
      run: echo ::set-env name=VERSION::$(mvn -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec -q)

    - name: Build Image
      run: docker build -t allanweber/candidates-career:${VERSION} .

    - name: Login to Heroku Container registry
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:login

#    - name: Docker Login
#      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

#    - name: Push Version
#      run: docker push allanweber/candidates-career:${VERSION}

#    - name: Build Latest Image and Push (only master)
#      if: github.ref == 'refs/heads/master'
#      run: |
#        docker tag allanweber/candidates-career:${VERSION} allanweber/candidates-career:latest
#        docker push allanweber/candidates-career:latest

#  heroku-deploy:
#    name: Heroku Deploy
#    runs-on: ubuntu-latest
#    needs: build
#    if: github.ref != 'refs/heads/master'
#    env:
#      HEROKU_API_KEY: ${{ secrets.HEROKU_SECRET }}
#    steps:
#    - name: Checkout
#      uses: actions/checkout@v1
#
#    - name: Push to Heroku Branch
#      run: git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/career-java-api-branch.git $GITHUB_SHA:master
