name: Java CI with Maven to Heroku

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      env:
        MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
      with:
        java-version: 1.11
    - name: Build with Maven
      run: mvn -B clean package -DMONGO_PASSWORD=$MONGO_PASSWORD --file pom.xml

  heroku-deploy-branch:
    name: Heroku Deploy Branch
    runs-on: ubuntu-latest
    needs: build
    if: github.ref != 'refs/heads/master'
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Push to Heroku Branch
      run: git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/candidates-career-dev.git $GITHUB_SHA:refs/heads/master

  heroku-deploy-prd:
    name: Heroku Deploy Production
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Push to Heroku Branch
        run: git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/candidates-career.git $GITHUB_SHA:refs/heads/master
